export const METRC_EVALUATION_DEFAULT_PACKAGE_LABEL = "AAA00090000196B000000001";
export const METRC_EVALUATION_DEFAULT_PACKAGE_ID = "46601";
export const METRC_EVALUATION_DEFAULT_PACKAGE_LICENSE = "SF-SBX-CO-7-13402";
/** Fallback UOM when evaluation package 46601 is not yet synced. */
export const METRC_EVALUATION_DEFAULT_PACKAGE_UNIT = "Kilograms";

export const METRC_EVALUATION_DEFAULT_ADJUSTMENT_REASON = "Entry Error";
