import { Router } from "express";
import { authMiddleware } from "./middleware/auth.js";
import { companyContextMiddleware } from "./middleware/companyContext.js";
import { asyncHandler } from "./middleware/asyncHandler.js";
import { authRouter } from "./modules/auth/routes.js";
import { companiesRouter } from "./modules/companies/routes.js";
import { workflowRouter } from "./modules/workflow/routes.js";
import { laborRouter } from "./modules/labor/routes.js";
import { auditRouter } from "./modules/audit/routes.js";
import { adminRouter } from "./modules/admin/routes.js";
import { configRouter } from "./modules/config/routes.js";
import { tasksRouter } from "./modules/tasks/routes.js";
import { dashboardRouter } from "./modules/dashboard/routes.js";
import { dataHubRouter } from "./modules/dataHub/routes.js";
import { activityRouter } from "./modules/activity/routes.js";
import { storeRouter } from "./modules/store/routes.js";
import { checksRouter } from "./modules/checks/routes.js";
import { cashLogRouter } from "./modules/cashLog/routes.js";
import { legacyCpuRouter } from "./modules/legacyCpu/routes.js";
import { sectionCalendarRouter } from "./modules/sectionCalendar/routes.js";
import { analyticsRouter } from "./modules/analytics/routes.js";
import { nexbatchRouter } from "./modules/nexbatch/routes.js";
import { extractionAssistRouter } from "./modules/extractionAssist/routes.js";
import { harvestSheetRouter } from "./modules/harvestSheet/routes.js";
import { internalJobsRouter } from "./modules/internal/jobsRoutes.js";
import { metrcRouter } from "./modules/metrc/routes.js";
import { autogrowRouter } from "./modules/autogrow/routes.js";
import { inventoryRouter } from "./modules/inventory/routes.js";
import { ordersRouter } from "./modules/orders/routes.js";
import { notificationsRouter } from "./modules/notifications/routes.js";
import { messagingRouter } from "./modules/messaging/routes.js";
import { portalRouter } from "./modules/portal/routes.js";
import { facilityMaintenanceRouter } from "./modules/facilityMaintenance/routes.js";
import { ediblesRouter } from "./modules/edibles/routes.js";
import { salesRouter } from "./modules/sales/routes.js";
export const appRouter = Router();
appRouter.use("/auth", authRouter);
/** Cron / worker hooks (Bearer CRON_SECRET) — must not run behind JWT. */
appRouter.use("/internal/jobs", internalJobsRouter);
appRouter.use(authMiddleware);
appRouter.use(asyncHandler(companyContextMiddleware));
appRouter.use("/companies", companiesRouter);
appRouter.use("/portal", portalRouter);
appRouter.use("/sales", salesRouter);
appRouter.use("/nexbatch", nexbatchRouter);
appRouter.use("/workflow", workflowRouter);
appRouter.use("/labor", laborRouter);
appRouter.use("/audit", auditRouter);
appRouter.use("/admin", adminRouter);
appRouter.use("/config", configRouter);
appRouter.use("/metrc", metrcRouter);
appRouter.use("/autogrow", autogrowRouter);
appRouter.use("/inventory", inventoryRouter);
appRouter.use("/orders", ordersRouter);
appRouter.use("/notifications", notificationsRouter);
appRouter.use("/messaging", messagingRouter);
appRouter.use("/tasks", tasksRouter);
appRouter.use("/dashboard", dashboardRouter);
appRouter.use("/facility-maintenance", facilityMaintenanceRouter);
appRouter.use("/edibles", ediblesRouter);
appRouter.use("/data-hub", dataHubRouter);
appRouter.use("/activity", activityRouter);
appRouter.use("/store", storeRouter);
/** Legacy CPU web app called `/api/sync` against the old Express server. */
appRouter.use("/sync", storeRouter);
appRouter.use("/checks", checksRouter);
appRouter.use("/cash-log", cashLogRouter);
appRouter.use("/extraction-assist", extractionAssistRouter);
appRouter.use("/harvest-sheet", harvestSheetRouter);
appRouter.use("/analytics", analyticsRouter);
appRouter.use("/section-calendar", sectionCalendarRouter);
/** Legacy SPA paths (`/api/cultivation`, `/api/logs`, …) used before `@cpu/api` workflow router. */
appRouter.use(legacyCpuRouter);
