import { Router } from "express";
import { authMiddleware } from "./middleware/auth.js";
import { authRouter } from "./modules/auth/routes.js";
import { companiesRouter } from "./modules/companies/routes.js";
import { workflowRouter } from "./modules/workflow/routes.js";
import { laborRouter } from "./modules/labor/routes.js";
import { auditRouter } from "./modules/audit/routes.js";
import { adminRouter } from "./modules/admin/routes.js";
import { configRouter } from "./modules/config/routes.js";
import { tasksRouter } from "./modules/tasks/routes.js";
import { dashboardRouter } from "./modules/dashboard/routes.js";
import { dataHubRouter } from "./modules/dataHub/routes.js";
import { activityRouter } from "./modules/activity/routes.js";
import { storeRouter } from "./modules/store/routes.js";
import { checksRouter } from "./modules/checks/routes.js";
export const appRouter = Router();
appRouter.use("/auth", authRouter);
appRouter.use(authMiddleware);
appRouter.use("/companies", companiesRouter);
appRouter.use("/workflow", workflowRouter);
appRouter.use("/labor", laborRouter);
appRouter.use("/audit", auditRouter);
appRouter.use("/admin", adminRouter);
appRouter.use("/config", configRouter);
appRouter.use("/tasks", tasksRouter);
appRouter.use("/dashboard", dashboardRouter);
appRouter.use("/data-hub", dataHubRouter);
appRouter.use("/activity", activityRouter);
appRouter.use("/store", storeRouter);
/** Legacy CPU web app called `/api/sync` against the old Express server. */
appRouter.use("/sync", storeRouter);
appRouter.use("/checks", checksRouter);
